# Generated by Django 4.2 on 2023-06-23 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_alter_user_id_comment_bid_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 13, 19, 20, 601810, tzinfo=datetime.timezone.utc)),
        ),
    ]
