# Generated by Django 4.2 on 2023-06-23 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Chicago', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 16, 29, 36, 917005, tzinfo=datetime.timezone.utc)),
        ),
    ]
