# Generated by Django 4.2 on 2023-06-23 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_timezone_alter_listing_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 17, 42, 33, 120003, tzinfo=datetime.timezone.utc)),
        ),
    ]
