# Generated by Django 4.2 on 2023-06-23 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_user_timezone_alter_listing_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 19, 47, 55, 780274, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 19, 47, 55, 776387, tzinfo=datetime.timezone.utc)),
        ),
    ]
