# Generated by Django 4.2 on 2023-06-23 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_time_created_alter_listing_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 21, 32, 0, 565455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('', 'Select'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('home', 'Home'), ('furniture', 'Furniture'), ('vehicles', 'Vehicles'), ('toys', 'Toys'), ('sports', 'Sports'), ('beauty', 'Beauty'), ('jewelry', 'Jewelry'), ('health', 'Health'), ('music', 'Music'), ('movies', 'Movies'), ('games', 'Games'), ('collectibles', 'Collectibles'), ('art', 'Art'), ('crafts', 'Crafts'), ('food', 'Food'), ('pets', 'Pets'), ('garden', 'Garden'), ('tools', 'Tools'), ('office', 'Office'), ('education', 'Education'), ('travel', 'Travel'), ('outdoor', 'Outdoor'), ('technology', 'Technology'), ('instruments', 'Instruments'), ('antiques', 'Antiques'), ('services', 'Services'), ('other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 21, 32, 0, 560694, tzinfo=datetime.timezone.utc)),
        ),
    ]
