# Generated by Django 4.2 on 2023-06-23 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_time_created_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 21, 50, 45, 366923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('', 'Select'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home', 'Home'), ('Furniture', 'Furniture'), ('Vehicles', 'Vehicles'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Beauty', 'Beauty'), ('Jewelry', 'Jewelry'), ('Health', 'Health'), ('Music', 'Music'), ('Movies', 'Movies'), ('Games', 'Games'), ('Collectibles', 'Collectibles'), ('Art', 'Art'), ('Crafts', 'Crafts'), ('Food', 'Food'), ('Pets', 'Pets'), ('Garden', 'Garden'), ('Tools', 'Tools'), ('Office', 'Office'), ('Education', 'Education'), ('Travel', 'Travel'), ('Outdoor', 'Outdoor'), ('Technology', 'Technology'), ('Instruments', 'Instruments'), ('Antiques', 'Antiques'), ('Services', 'Services'), ('other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 21, 50, 45, 361717, tzinfo=datetime.timezone.utc)),
        ),
    ]
