# Generated by Django 4.2 on 2023-06-26 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bid_listing_alter_comment_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 22, 29, 56, 552104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 22, 29, 56, 553837, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 22, 29, 56, 547514, tzinfo=datetime.timezone.utc)),
        ),
    ]
