# Generated by Django 4.2 on 2023-06-27 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_time_created_alter_comment_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 13, 23, 14, 791939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 13, 23, 14, 785706, tzinfo=datetime.timezone.utc)),
        ),
    ]
