# Generated by Django 4.2 on 2023-06-28 02:04

import auctions.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_comment_time_created_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 2, 4, 11, 410546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='/auctions/static/auctions/images/default.jpg', upload_to=auctions.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 2, 4, 11, 403969, tzinfo=datetime.timezone.utc)),
        ),
    ]
