# Generated by Django 4.2 on 2023-06-28 21:27

import auctions.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_comment_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 21, 27, 17, 63956, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to=auctions.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 21, 27, 17, 59028, tzinfo=datetime.timezone.utc)),
        ),
    ]
