# Generated by Django 4.2 on 2023-06-28 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_bid_amount_alter_comment_time_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='brand',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 22, 30, 4, 150926, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 22, 30, 4, 144429, tzinfo=datetime.timezone.utc)),
        ),
    ]
