# Generated by Django 4.2 on 2023-07-08 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_alter_comment_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 15, 40, 12, 513951, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 15, 40, 12, 507954, tzinfo=datetime.timezone.utc)),
        ),
    ]
