# Generated by Django 5.0.4 on 2024-04-05 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_comment_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 12, 27, 48, 55138, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 12, 27, 48, 50496, tzinfo=datetime.timezone.utc)),
        ),
    ]
